name: Get Link From Telegram Input
on:
  workflow_dispatch:
    inputs:
      match_url:
        description: 'Dán link trận đấu'
        required: true
      match_name:
        description: 'Nhập tên trận đấu (Ví dụ: MU vs Barca)'
        required: true
        default: 'Link'
      chat_id:
        description: 'ID Telegram của người gửi'
        required: true

jobs:
  check_link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 1. Cài đặt các thư viện Python cần thiết
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright

      # 2. Cài đặt trình duyệt Chromium và các thư viện hệ thống cho Playwright
      - name: Install Playwright Browsers
        run: playwright install chromium --with-deps

      - name: Run script
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ github.event.inputs.chat_id }}
          MATCH_URL: ${{ github.event.inputs.match_url }}
          MATCH_NAME: ${{ github.event.inputs.match_name }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_KV_NAMESPACE_ID: ${{ secrets.CF_KV_NAMESPACE_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: python buncha.py
